/* Generated by Yosys 0.23+35 (git sha1 23e26ff66, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module mult8(a, y);
  input [2:0] a;
  wire [2:0] a;
  output [5:0] y;
  wire [5:0] y;
  assign y = { a, a };
endmodule
