/* Generated by Yosys 0.23+35 (git sha1 23e26ff66, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "multiple_modules.v:10.1-14.10" *)
module multiple_modules(a, b, c, y);
  (* src = "multiple_modules.v:10.32-10.33" *)
  input a;
  wire a;
  (* src = "multiple_modules.v:10.41-10.42" *)
  input b;
  wire b;
  (* src = "multiple_modules.v:10.50-10.51" *)
  input c;
  wire c;
  (* src = "multiple_modules.v:11.7-11.11" *)
  wire net1;
  (* src = "multiple_modules.v:10.61-10.62" *)
  output y;
  wire y;
  (* module_not_derived = 32'd1 *)
  (* src = "multiple_modules.v:12.14-12.38" *)
  sub_module1 u1 (
    .a(a),
    .b(b),
    .y(net1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "multiple_modules.v:13.14-13.38" *)
  sub_module2 u2 (
    .a(net1),
    .b(c),
    .y(y)
  );
endmodule

(* src = "multiple_modules.v:5.1-7.10" *)
module sub_module1(a, b, y);
  (* src = "multiple_modules.v:5.27-5.28" *)
  wire _0_;
  (* src = "multiple_modules.v:5.36-5.37" *)
  wire _1_;
  (* src = "multiple_modules.v:5.46-5.47" *)
  wire _2_;
  (* src = "multiple_modules.v:5.27-5.28" *)
  input a;
  wire a;
  (* src = "multiple_modules.v:5.36-5.37" *)
  input b;
  wire b;
  (* src = "multiple_modules.v:5.46-5.47" *)
  output y;
  wire y;
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule

(* src = "multiple_modules.v:1.1-3.10" *)
module sub_module2(a, b, y);
  (* src = "multiple_modules.v:1.27-1.28" *)
  wire _0_;
  (* src = "multiple_modules.v:1.36-1.37" *)
  wire _1_;
  (* src = "multiple_modules.v:1.46-1.47" *)
  wire _2_;
  (* src = "multiple_modules.v:1.27-1.28" *)
  input a;
  wire a;
  (* src = "multiple_modules.v:1.36-1.37" *)
  input b;
  wire b;
  (* src = "multiple_modules.v:1.46-1.47" *)
  output y;
  wire y;
  sky130_fd_sc_hd__or2_0 _3_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
